apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: influxdb-volume
    labels:
        type: local
        volume-svc: influxdb
spec:
    storageClassName: manual
    capacity:
        storage: 500Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/mnt/influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: influxdb-volume-claim
    labels:
        app: influxdb
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 400Mi
    selector:
        matchLabels:
            type: local
            volume-svc: influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb_image # имя имейджа
          imagePullPolicy: Never # запрещаем искать в докер хабе
          ports:
            - containerPort: 8086
          volumeMounts:
              - name: influxdb-volume
                mountPath: /root/.influxdb
      volumes:
          - name: influxdb-volume
            persistentVolumeClaim:
                claimName: influxdb-volume-claim
